/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthMyPortfolioRouteRouteImport } from './routes/_auth/my-portfolio/route'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthAdminAuthorsRouteImport } from './routes/_auth/admin/authors'
import { Route as AuthAdminPortfolioRouteRouteImport } from './routes/_auth/admin/portfolio/route'
import { Route as AuthAdminPublishedRouteImport } from './routes/_auth/admin/published'
import { Route as AuthAdminReviewRouteImport } from './routes/_auth/admin/review'
import { Route as AuthEditorSlugRouteImport } from './routes/_auth/editor/$slug'
import { Route as AuthEditorNewRouteImport } from './routes/_auth/editor/new'
import { Route as AuthMyPortfolioIndexRouteImport } from './routes/_auth/my-portfolio/index'
import { Route as AuthMyPortfolioExperienceRouteImport } from './routes/_auth/my-portfolio/experience'
import { Route as AuthMyPortfolioProjectsRouteImport } from './routes/_auth/my-portfolio/projects'
import { Route as AuthMyPortfolioSkillsRouteImport } from './routes/_auth/my-portfolio/skills'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAdminPortfolioIndexRouteImport } from './routes/_auth/admin/portfolio/index'
import { Route as AuthAdminPortfolioExperienceRouteImport } from './routes/_auth/admin/portfolio/experience'
import { Route as AuthAdminPortfolioProjectsRouteImport } from './routes/_auth/admin/portfolio/projects'
import { Route as AuthAdminPortfolioSkillsRouteImport } from './routes/_auth/admin/portfolio/skills'
import { Route as AuthAdminReviewSlugRouteImport } from './routes/_auth/admin/review_.$slug'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMyPortfolioRouteRoute = AuthMyPortfolioRouteRouteImport.update({
  id: '/my-portfolio',
  path: '/my-portfolio',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminAuthorsRoute = AuthAdminAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminPortfolioRouteRoute = AuthAdminPortfolioRouteRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminPublishedRoute = AuthAdminPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminReviewRoute = AuthAdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthEditorSlugRoute = AuthEditorSlugRouteImport.update({
  id: '/editor/$slug',
  path: '/editor/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEditorNewRoute = AuthEditorNewRouteImport.update({
  id: '/editor/new',
  path: '/editor/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMyPortfolioIndexRoute = AuthMyPortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMyPortfolioRouteRoute,
} as any)
const AuthMyPortfolioExperienceRoute =
  AuthMyPortfolioExperienceRouteImport.update({
    id: '/experience',
    path: '/experience',
    getParentRoute: () => AuthMyPortfolioRouteRoute,
  } as any)
const AuthMyPortfolioProjectsRoute = AuthMyPortfolioProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthMyPortfolioRouteRoute,
} as any)
const AuthMyPortfolioSkillsRoute = AuthMyPortfolioSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthMyPortfolioRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminPortfolioIndexRoute = AuthAdminPortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminPortfolioRouteRoute,
} as any)
const AuthAdminPortfolioExperienceRoute =
  AuthAdminPortfolioExperienceRouteImport.update({
    id: '/experience',
    path: '/experience',
    getParentRoute: () => AuthAdminPortfolioRouteRoute,
  } as any)
const AuthAdminPortfolioProjectsRoute =
  AuthAdminPortfolioProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthAdminPortfolioRouteRoute,
  } as any)
const AuthAdminPortfolioSkillsRoute =
  AuthAdminPortfolioSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthAdminPortfolioRouteRoute,
  } as any)
const AuthAdminReviewSlugRoute = AuthAdminReviewSlugRouteImport.update({
  id: '/review_/$slug',
  path: '/review/$slug',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/my-portfolio': typeof AuthMyPortfolioRouteRouteWithChildren
  '/admin/portfolio': typeof AuthAdminPortfolioRouteRouteWithChildren
  '/admin/authors': typeof AuthAdminAuthorsRoute
  '/admin/published': typeof AuthAdminPublishedRoute
  '/admin/review': typeof AuthAdminReviewRoute
  '/editor/$slug': typeof AuthEditorSlugRoute
  '/editor/new': typeof AuthEditorNewRoute
  '/my-portfolio/experience': typeof AuthMyPortfolioExperienceRoute
  '/my-portfolio/projects': typeof AuthMyPortfolioProjectsRoute
  '/my-portfolio/skills': typeof AuthMyPortfolioSkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/my-portfolio/': typeof AuthMyPortfolioIndexRoute
  '/admin/portfolio/experience': typeof AuthAdminPortfolioExperienceRoute
  '/admin/portfolio/projects': typeof AuthAdminPortfolioProjectsRoute
  '/admin/portfolio/skills': typeof AuthAdminPortfolioSkillsRoute
  '/admin/review/$slug': typeof AuthAdminReviewSlugRoute
  '/admin/portfolio/': typeof AuthAdminPortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/reset-password': typeof ResetPasswordRoute
  '/': typeof AuthIndexRoute
  '/admin/authors': typeof AuthAdminAuthorsRoute
  '/admin/published': typeof AuthAdminPublishedRoute
  '/admin/review': typeof AuthAdminReviewRoute
  '/editor/$slug': typeof AuthEditorSlugRoute
  '/editor/new': typeof AuthEditorNewRoute
  '/my-portfolio/experience': typeof AuthMyPortfolioExperienceRoute
  '/my-portfolio/projects': typeof AuthMyPortfolioProjectsRoute
  '/my-portfolio/skills': typeof AuthMyPortfolioSkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthAdminIndexRoute
  '/my-portfolio': typeof AuthMyPortfolioIndexRoute
  '/admin/portfolio/experience': typeof AuthAdminPortfolioExperienceRoute
  '/admin/portfolio/projects': typeof AuthAdminPortfolioProjectsRoute
  '/admin/portfolio/skills': typeof AuthAdminPortfolioSkillsRoute
  '/admin/review/$slug': typeof AuthAdminReviewSlugRoute
  '/admin/portfolio': typeof AuthAdminPortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/my-portfolio': typeof AuthMyPortfolioRouteRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/portfolio': typeof AuthAdminPortfolioRouteRouteWithChildren
  '/_auth/admin/authors': typeof AuthAdminAuthorsRoute
  '/_auth/admin/published': typeof AuthAdminPublishedRoute
  '/_auth/admin/review': typeof AuthAdminReviewRoute
  '/_auth/editor/$slug': typeof AuthEditorSlugRoute
  '/_auth/editor/new': typeof AuthEditorNewRoute
  '/_auth/my-portfolio/experience': typeof AuthMyPortfolioExperienceRoute
  '/_auth/my-portfolio/projects': typeof AuthMyPortfolioProjectsRoute
  '/_auth/my-portfolio/skills': typeof AuthMyPortfolioSkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/my-portfolio/': typeof AuthMyPortfolioIndexRoute
  '/_auth/admin/portfolio/experience': typeof AuthAdminPortfolioExperienceRoute
  '/_auth/admin/portfolio/projects': typeof AuthAdminPortfolioProjectsRoute
  '/_auth/admin/portfolio/skills': typeof AuthAdminPortfolioSkillsRoute
  '/_auth/admin/review_/$slug': typeof AuthAdminReviewSlugRoute
  '/_auth/admin/portfolio/': typeof AuthAdminPortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/my-portfolio'
    | '/admin/portfolio'
    | '/admin/authors'
    | '/admin/published'
    | '/admin/review'
    | '/editor/$slug'
    | '/editor/new'
    | '/my-portfolio/experience'
    | '/my-portfolio/projects'
    | '/my-portfolio/skills'
    | '/api/auth/$'
    | '/admin/'
    | '/my-portfolio/'
    | '/admin/portfolio/experience'
    | '/admin/portfolio/projects'
    | '/admin/portfolio/skills'
    | '/admin/review/$slug'
    | '/admin/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset-password'
    | '/'
    | '/admin/authors'
    | '/admin/published'
    | '/admin/review'
    | '/editor/$slug'
    | '/editor/new'
    | '/my-portfolio/experience'
    | '/my-portfolio/projects'
    | '/my-portfolio/skills'
    | '/api/auth/$'
    | '/admin'
    | '/my-portfolio'
    | '/admin/portfolio/experience'
    | '/admin/portfolio/projects'
    | '/admin/portfolio/skills'
    | '/admin/review/$slug'
    | '/admin/portfolio'
  id:
    | '__root__'
    | '/_auth'
    | '/reset-password'
    | '/_auth/admin'
    | '/_auth/my-portfolio'
    | '/_auth/'
    | '/_auth/admin/portfolio'
    | '/_auth/admin/authors'
    | '/_auth/admin/published'
    | '/_auth/admin/review'
    | '/_auth/editor/$slug'
    | '/_auth/editor/new'
    | '/_auth/my-portfolio/experience'
    | '/_auth/my-portfolio/projects'
    | '/_auth/my-portfolio/skills'
    | '/api/auth/$'
    | '/_auth/admin/'
    | '/_auth/my-portfolio/'
    | '/_auth/admin/portfolio/experience'
    | '/_auth/admin/portfolio/projects'
    | '/_auth/admin/portfolio/skills'
    | '/_auth/admin/review_/$slug'
    | '/_auth/admin/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/my-portfolio': {
      id: '/_auth/my-portfolio'
      path: '/my-portfolio'
      fullPath: '/my-portfolio'
      preLoaderRoute: typeof AuthMyPortfolioRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/authors': {
      id: '/_auth/admin/authors'
      path: '/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AuthAdminAuthorsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/portfolio': {
      id: '/_auth/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AuthAdminPortfolioRouteRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/published': {
      id: '/_auth/admin/published'
      path: '/published'
      fullPath: '/admin/published'
      preLoaderRoute: typeof AuthAdminPublishedRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/review': {
      id: '/_auth/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AuthAdminReviewRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/editor/$slug': {
      id: '/_auth/editor/$slug'
      path: '/editor/$slug'
      fullPath: '/editor/$slug'
      preLoaderRoute: typeof AuthEditorSlugRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/editor/new': {
      id: '/_auth/editor/new'
      path: '/editor/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof AuthEditorNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/my-portfolio/': {
      id: '/_auth/my-portfolio/'
      path: '/'
      fullPath: '/my-portfolio/'
      preLoaderRoute: typeof AuthMyPortfolioIndexRouteImport
      parentRoute: typeof AuthMyPortfolioRouteRoute
    }
    '/_auth/my-portfolio/experience': {
      id: '/_auth/my-portfolio/experience'
      path: '/experience'
      fullPath: '/my-portfolio/experience'
      preLoaderRoute: typeof AuthMyPortfolioExperienceRouteImport
      parentRoute: typeof AuthMyPortfolioRouteRoute
    }
    '/_auth/my-portfolio/projects': {
      id: '/_auth/my-portfolio/projects'
      path: '/projects'
      fullPath: '/my-portfolio/projects'
      preLoaderRoute: typeof AuthMyPortfolioProjectsRouteImport
      parentRoute: typeof AuthMyPortfolioRouteRoute
    }
    '/_auth/my-portfolio/skills': {
      id: '/_auth/my-portfolio/skills'
      path: '/skills'
      fullPath: '/my-portfolio/skills'
      preLoaderRoute: typeof AuthMyPortfolioSkillsRouteImport
      parentRoute: typeof AuthMyPortfolioRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin/portfolio/': {
      id: '/_auth/admin/portfolio/'
      path: '/'
      fullPath: '/admin/portfolio/'
      preLoaderRoute: typeof AuthAdminPortfolioIndexRouteImport
      parentRoute: typeof AuthAdminPortfolioRouteRoute
    }
    '/_auth/admin/portfolio/experience': {
      id: '/_auth/admin/portfolio/experience'
      path: '/experience'
      fullPath: '/admin/portfolio/experience'
      preLoaderRoute: typeof AuthAdminPortfolioExperienceRouteImport
      parentRoute: typeof AuthAdminPortfolioRouteRoute
    }
    '/_auth/admin/portfolio/projects': {
      id: '/_auth/admin/portfolio/projects'
      path: '/projects'
      fullPath: '/admin/portfolio/projects'
      preLoaderRoute: typeof AuthAdminPortfolioProjectsRouteImport
      parentRoute: typeof AuthAdminPortfolioRouteRoute
    }
    '/_auth/admin/portfolio/skills': {
      id: '/_auth/admin/portfolio/skills'
      path: '/skills'
      fullPath: '/admin/portfolio/skills'
      preLoaderRoute: typeof AuthAdminPortfolioSkillsRouteImport
      parentRoute: typeof AuthAdminPortfolioRouteRoute
    }
    '/_auth/admin/review_/$slug': {
      id: '/_auth/admin/review_/$slug'
      path: '/review/$slug'
      fullPath: '/admin/review/$slug'
      preLoaderRoute: typeof AuthAdminReviewSlugRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
  }
}

interface AuthAdminPortfolioRouteRouteChildren {
  AuthAdminPortfolioExperienceRoute: typeof AuthAdminPortfolioExperienceRoute
  AuthAdminPortfolioProjectsRoute: typeof AuthAdminPortfolioProjectsRoute
  AuthAdminPortfolioSkillsRoute: typeof AuthAdminPortfolioSkillsRoute
  AuthAdminPortfolioIndexRoute: typeof AuthAdminPortfolioIndexRoute
}

const AuthAdminPortfolioRouteRouteChildren: AuthAdminPortfolioRouteRouteChildren =
  {
    AuthAdminPortfolioExperienceRoute: AuthAdminPortfolioExperienceRoute,
    AuthAdminPortfolioProjectsRoute: AuthAdminPortfolioProjectsRoute,
    AuthAdminPortfolioSkillsRoute: AuthAdminPortfolioSkillsRoute,
    AuthAdminPortfolioIndexRoute: AuthAdminPortfolioIndexRoute,
  }

const AuthAdminPortfolioRouteRouteWithChildren =
  AuthAdminPortfolioRouteRoute._addFileChildren(
    AuthAdminPortfolioRouteRouteChildren,
  )

interface AuthAdminRouteRouteChildren {
  AuthAdminPortfolioRouteRoute: typeof AuthAdminPortfolioRouteRouteWithChildren
  AuthAdminAuthorsRoute: typeof AuthAdminAuthorsRoute
  AuthAdminPublishedRoute: typeof AuthAdminPublishedRoute
  AuthAdminReviewRoute: typeof AuthAdminReviewRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthAdminReviewSlugRoute: typeof AuthAdminReviewSlugRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminPortfolioRouteRoute: AuthAdminPortfolioRouteRouteWithChildren,
  AuthAdminAuthorsRoute: AuthAdminAuthorsRoute,
  AuthAdminPublishedRoute: AuthAdminPublishedRoute,
  AuthAdminReviewRoute: AuthAdminReviewRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthAdminReviewSlugRoute: AuthAdminReviewSlugRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthMyPortfolioRouteRouteChildren {
  AuthMyPortfolioExperienceRoute: typeof AuthMyPortfolioExperienceRoute
  AuthMyPortfolioProjectsRoute: typeof AuthMyPortfolioProjectsRoute
  AuthMyPortfolioSkillsRoute: typeof AuthMyPortfolioSkillsRoute
  AuthMyPortfolioIndexRoute: typeof AuthMyPortfolioIndexRoute
}

const AuthMyPortfolioRouteRouteChildren: AuthMyPortfolioRouteRouteChildren = {
  AuthMyPortfolioExperienceRoute: AuthMyPortfolioExperienceRoute,
  AuthMyPortfolioProjectsRoute: AuthMyPortfolioProjectsRoute,
  AuthMyPortfolioSkillsRoute: AuthMyPortfolioSkillsRoute,
  AuthMyPortfolioIndexRoute: AuthMyPortfolioIndexRoute,
}

const AuthMyPortfolioRouteRouteWithChildren =
  AuthMyPortfolioRouteRoute._addFileChildren(AuthMyPortfolioRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthMyPortfolioRouteRoute: typeof AuthMyPortfolioRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthEditorSlugRoute: typeof AuthEditorSlugRoute
  AuthEditorNewRoute: typeof AuthEditorNewRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthMyPortfolioRouteRoute: AuthMyPortfolioRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthEditorSlugRoute: AuthEditorSlugRoute,
  AuthEditorNewRoute: AuthEditorNewRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
